name: Repo

on:
  push:
    branches: [master]

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge master -> develop
        uses: everlytic/branch-merge@master
        with:
          target_branch: develop
          github_token: ${{ secrets.REPO_TOKEN }}
